# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: peerdas-devnet-0
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        peerdas-devnet-0: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.bootnode-1.srv.peerdas-devnet-0.ethpandaops.io
    clientArgs:
      networks:
        peerdas-devnet-0:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://cc107726929445f56ea04709177c0abaf13ce8ffa45ffe0a7aaa890c8a5a2031cbc7d0e1123cb6c65d5eaab7a5b0c9ceecd81d8e97e72ccb1c7253fed8c4b4f6@159.223.150.131:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>@ethstats.peerdas-devnet-0.ethpandaops.io:443
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://cc107726929445f56ea04709177c0abaf13ce8ffa45ffe0a7aaa890c8a5a2031cbc7d0e1123cb6c65d5eaab7a5b0c9ceecd81d8e97e72ccb1c7253fed8c4b4f6@159.223.150.131:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none.cfg
              - --EthStats.Enabled=true
              - --EthStats.Name=k8s-teku-geth-001
              - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>
              - --EthStats.Server=wss://ethstats.peerdas-devnet-0.ethpandaops.io/api/
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Seq.ServerUrl=https://seq.nethermind.io
              - --Seq.ApiKey=yuOqjKOHhZCw2D2U7pmL
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --state.scheme=path
              - --networkid=7071720988
              - --syncmode=full
              - --bootnodes=enode://cc107726929445f56ea04709177c0abaf13ce8ffa45ffe0a7aaa890c8a5a2031cbc7d0e1123cb6c65d5eaab7a5b0c9ceecd81d8e97e72ccb1c7253fed8c4b4f6@159.223.150.131:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>@ethstats.peerdas-devnet-0.ethpandaops.io
              - --rpc.allow-unprotected-txs
            erigon:
              - --chain=dev
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool
              - --http.vhosts=*
              - --ws
              - --prune=htc
              - --networkid=7071720988
              - --db.size.limit=500GB
              - --bootnodes=enode://cc107726929445f56ea04709177c0abaf13ce8ffa45ffe0a7aaa890c8a5a2031cbc7d0e1123cb6c65d5eaab7a5b0c9ceecd81d8e97e72ccb1c7253fed8c4b4f6@159.223.150.131:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>@ethstats.peerdas-devnet-0.ethpandaops.io
            ethereumjs:
              - --gethGenesis=/data/network-config/genesis.json
              - --bootnodes=enode://cc107726929445f56ea04709177c0abaf13ce8ffa45ffe0a7aaa890c8a5a2031cbc7d0e1123cb6c65d5eaab7a5b0c9ceecd81d8e97e72ccb1c7253fed8c4b4f6@159.223.150.131:30303?discport=30303
              - --maxPeers=75
              - --isSingleNode=true
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QNVAHmD3RRkaUm-5lIP-Fxtqte8EDy_XIajF-9yhJgJmaEiF-uexT-SWBLhfAvC0nCy7zD0fueGZvoPqloLWPaiGAY98xBw2gmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-LK4QA02kK2wuFWKqBhmO_olytnhy4zfTTwyp2TErnR00RjFbUU-DCEzOF_jTT2zcI_VGoJkAQn5OBuH2mYKtpJAoCsEh2F0dG5ldHOIAIABAAAAAACEZXRoMpBrZne0YFghlQB0O6QLAAAAgmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQLbp2B5JcxeVN-QZcp7Ye28RdHVi9Pp0Q21m8UKqMimR4N0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --data-storage-mode=ARCHIVE
              - --Xepochs-store-blobs=max # Keep the blobs forever
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QNVAHmD3RRkaUm-5lIP-Fxtqte8EDy_XIajF-9yhJgJmaEiF-uexT-SWBLhfAvC0nCy7zD0fueGZvoPqloLWPaiGAY98xBw2gmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QA02kK2wuFWKqBhmO_olytnhy4zfTTwyp2TErnR00RjFbUU-DCEzOF_jTT2zcI_VGoJkAQn5OBuH2mYKtpJAoCsEh2F0dG5ldHOIAIABAAAAAACEZXRoMpBrZne0YFghlQB0O6QLAAAAgmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQLbp2B5JcxeVN-QZcp7Ye28RdHVi9Pp0Q21m8UKqMimR4N0Y3CCIyiDdWRwgiMo
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QNVAHmD3RRkaUm-5lIP-Fxtqte8EDy_XIajF-9yhJgJmaEiF-uexT-SWBLhfAvC0nCy7zD0fueGZvoPqloLWPaiGAY98xBw2gmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-LK4QA02kK2wuFWKqBhmO_olytnhy4zfTTwyp2TErnR00RjFbUU-DCEzOF_jTT2zcI_VGoJkAQn5OBuH2mYKtpJAoCsEh2F0dG5ldHOIAIABAAAAAACEZXRoMpBrZne0YFghlQB0O6QLAAAAgmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQLbp2B5JcxeVN-QZcp7Ye28RdHVi9Pp0Q21m8UKqMimR4N0Y3CCIyiDdWRwgiMo
              - --allow-insecure-genesis-sync
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=INFO
              - --light-client-data-serve=false
              - --graffiti=Barnabass-MacBook-Pro
              - --bootstrap-node=enr:-Iq4QNVAHmD3RRkaUm-5lIP-Fxtqte8EDy_XIajF-9yhJgJmaEiF-uexT-SWBLhfAvC0nCy7zD0fueGZvoPqloLWPaiGAY98xBw2gmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QA02kK2wuFWKqBhmO_olytnhy4zfTTwyp2TErnR00RjFbUU-DCEzOF_jTT2zcI_VGoJkAQn5OBuH2mYKtpJAoCsEh2F0dG5ldHOIAIABAAAAAACEZXRoMpBrZne0YFghlQB0O6QLAAAAgmlkgnY0gmlwhJ_floOJc2VjcDI1NmsxoQLbp2B5JcxeVN-QZcp7Ye28RdHVi9Pp0Q21m8UKqMimR4N0Y3CCIyiDdWRwgiMo


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: ethereum/client-go
      tag: stable
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: peerdas-devnet-0
      testnet: peerdas-devnet-0
      ethereum_network: peerdas-devnet-0
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.peerdas-devnet-0.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.peerdas-devnet-0.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.peerdas-devnet-0.ethpandaops.io/el/besu.json;
            BOOTNODES_URI=https://config.peerdas-devnet-0.ethpandaops.io/el/bootnodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/bootnodes.txt $BOOTNODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethereum/client-go:stable
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --state.scheme=path --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: consensys/teku
      tag: latest
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: peerdas-devnet-0
      testnet: peerdas-devnet-0
      ethereum_network: peerdas-devnet-0
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.peerdas-devnet-0.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.peerdas-devnet-0.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.peerdas-devnet-0.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.peerdas-devnet-0.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.peerdas-devnet-0.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.peerdas-devnet-0.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootnodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootnodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootnodes2.txt;
          mv /data/network-config/bootnodes2.txt /data/network-config/bootnodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
