# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: peerdas-devnet-1
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        peerdas-devnet-1: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.bootnode-1.srv.peerdas-devnet-1.ethpandaops.io
    clientArgs:
      networks:
        peerdas-devnet-1:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://fc17bb1cb6a0dcfe71c883467fb3899c0073e45acf4b78e4e30efde610859effa0db22c58369ee3bd60b5f41827c2c5a4e52ef61016e3168b94fc2d83911b984@167.99.5.231:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>@ethstats.peerdas-devnet-1.ethpandaops.io:443
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://fc17bb1cb6a0dcfe71c883467fb3899c0073e45acf4b78e4e30efde610859effa0db22c58369ee3bd60b5f41827c2c5a4e52ef61016e3168b94fc2d83911b984@167.99.5.231:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none.cfg
              - --EthStats.Enabled=true
              - --EthStats.Name=k8s-teku-geth-001
              - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>
              - --EthStats.Server=wss://ethstats.peerdas-devnet-1.ethpandaops.io/api/
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Seq.ServerUrl=https://seq.nethermind.io
              - --Seq.ApiKey=yuOqjKOHhZCw2D2U7pmL
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --state.scheme=path
              - --networkid=7068553372
              - --syncmode=full
              - --bootnodes=enode://fc17bb1cb6a0dcfe71c883467fb3899c0073e45acf4b78e4e30efde610859effa0db22c58369ee3bd60b5f41827c2c5a4e52ef61016e3168b94fc2d83911b984@167.99.5.231:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>@ethstats.peerdas-devnet-1.ethpandaops.io
              - --rpc.allow-unprotected-txs
            erigon:
              - --chain=dev
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool
              - --http.vhosts=*
              - --ws
              - --prune=htc
              - --networkid=7068553372
              - --db.size.limit=500GB
              - --bootnodes=enode://fc17bb1cb6a0dcfe71c883467fb3899c0073e45acf4b78e4e30efde610859effa0db22c58369ee3bd60b5f41827c2c5a4e52ef61016e3168b94fc2d83911b984@167.99.5.231:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.ethstats_secret}>@ethstats.peerdas-devnet-1.ethpandaops.io
            ethereumjs:
              - --gethGenesis=/data/network-config/genesis.json
              - --bootnodes=enode://fc17bb1cb6a0dcfe71c883467fb3899c0073e45acf4b78e4e30efde610859effa0db22c58369ee3bd60b5f41827c2c5a4e52ef61016e3168b94fc2d83911b984@167.99.5.231:30303?discport=30303
              - --maxPeers=75
              - --isSingleNode=true
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QPNG0oNNdtOhqDym34NlchSkGM8xXmO1paXzah6BNiVmSkB_J9xAqlOHIc8mFjBraesh_mROWkyzpTw-yt_pBh6GAZBPYtJngmlkgnY0gmlwhKdjBeeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-OK4QLamGv4mo4nYP2OVeGsNJfJOXhBIFpPy3PtbXUPnVcrOb-cGWAq4lMizbjupCsEhArAhQlJw1KEAlFEpSWVhrfMBh2F0dG5ldHOIAAAAAAAAAACUY3VzdG9keV9zdWJuZXRfY291bnSIQAAAAAAAAACEZXRoMpCsv8kuYIMmhwB0O6QLAAAAgmlkgnY0gmlwhKdjBeeEcXVpY4IjKYlzZWNwMjU2azGhAiWxmSTl3QUeyNDVe6yR5mScHzlaBxQRL4h-iZEyzaQRiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QPNG0oNNdtOhqDym34NlchSkGM8xXmO1paXzah6BNiVmSkB_J9xAqlOHIc8mFjBraesh_mROWkyzpTw-yt_pBh6GAZBPYtJngmlkgnY0gmlwhKdjBeeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-OK4QLamGv4mo4nYP2OVeGsNJfJOXhBIFpPy3PtbXUPnVcrOb-cGWAq4lMizbjupCsEhArAhQlJw1KEAlFEpSWVhrfMBh2F0dG5ldHOIAAAAAAAAAACUY3VzdG9keV9zdWJuZXRfY291bnSIQAAAAAAAAACEZXRoMpCsv8kuYIMmhwB0O6QLAAAAgmlkgnY0gmlwhKdjBeeEcXVpY4IjKYlzZWNwMjU2azGhAiWxmSTl3QUeyNDVe6yR5mScHzlaBxQRL4h-iZEyzaQRiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --p2p-subscribe-all-custody-subnets-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QPNG0oNNdtOhqDym34NlchSkGM8xXmO1paXzah6BNiVmSkB_J9xAqlOHIc8mFjBraesh_mROWkyzpTw-yt_pBh6GAZBPYtJngmlkgnY0gmlwhKdjBeeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-OK4QLamGv4mo4nYP2OVeGsNJfJOXhBIFpPy3PtbXUPnVcrOb-cGWAq4lMizbjupCsEhArAhQlJw1KEAlFEpSWVhrfMBh2F0dG5ldHOIAAAAAAAAAACUY3VzdG9keV9zdWJuZXRfY291bnSIQAAAAAAAAACEZXRoMpCsv8kuYIMmhwB0O6QLAAAAgmlkgnY0gmlwhKdjBeeEcXVpY4IjKYlzZWNwMjU2azGhAiWxmSTl3QUeyNDVe6yR5mScHzlaBxQRL4h-iZEyzaQRiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QPNG0oNNdtOhqDym34NlchSkGM8xXmO1paXzah6BNiVmSkB_J9xAqlOHIc8mFjBraesh_mROWkyzpTw-yt_pBh6GAZBPYtJngmlkgnY0gmlwhKdjBeeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-OK4QLamGv4mo4nYP2OVeGsNJfJOXhBIFpPy3PtbXUPnVcrOb-cGWAq4lMizbjupCsEhArAhQlJw1KEAlFEpSWVhrfMBh2F0dG5ldHOIAAAAAAAAAACUY3VzdG9keV9zdWJuZXRfY291bnSIQAAAAAAAAACEZXRoMpCsv8kuYIMmhwB0O6QLAAAAgmlkgnY0gmlwhKdjBeeEcXVpY4IjKYlzZWNwMjU2azGhAiWxmSTl3QUeyNDVe6yR5mScHzlaBxQRL4h-iZEyzaQRiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --allow-insecure-genesis-sync
              - --subscribe-all-data-column-subnets
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=INFO
              - --light-client-data-serve=false
              - --bootstrap-node=enr:-Iq4QPNG0oNNdtOhqDym34NlchSkGM8xXmO1paXzah6BNiVmSkB_J9xAqlOHIc8mFjBraesh_mROWkyzpTw-yt_pBh6GAZBPYtJngmlkgnY0gmlwhKdjBeeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-OK4QLamGv4mo4nYP2OVeGsNJfJOXhBIFpPy3PtbXUPnVcrOb-cGWAq4lMizbjupCsEhArAhQlJw1KEAlFEpSWVhrfMBh2F0dG5ldHOIAAAAAAAAAACUY3VzdG9keV9zdWJuZXRfY291bnSIQAAAAAAAAACEZXRoMpCsv8kuYIMmhwB0O6QLAAAAgmlkgnY0gmlwhKdjBeeEcXVpY4IjKYlzZWNwMjU2azGhAiWxmSTl3QUeyNDVe6yR5mScHzlaBxQRL4h-iZEyzaQRiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: ethereum/client-go
      tag: stable
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: peerdas-devnet-1
      testnet: peerdas-devnet-1
      ethereum_network: peerdas-devnet-1
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.peerdas-devnet-1.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.peerdas-devnet-1.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.peerdas-devnet-1.ethpandaops.io/el/besu.json;
            ENODES_URI=https://config.peerdas-devnet-1.ethpandaops.io/el/enodes.txt;
            mkdir -p /data/network-config/metadata;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/metadata/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/metadata/genesis.json $GENESIS_URI;
              wget -O /data/network-config/metadata/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/metadata/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/metadata/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethereum/client-go:stable
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --state.scheme=path --datadir /data /data/network-config/metadata/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: ethpandaops/teku
      tag: nashatyrev-das-3768eca
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: peerdas-devnet-1
      testnet: peerdas-devnet-1
      ethereum_network: peerdas-devnet-1
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.peerdas-devnet-1.ethpandaops.io/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.peerdas-devnet-1.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.peerdas-devnet-1.ethpandaops.io/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.peerdas-devnet-1.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.peerdas-devnet-1.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config/metadata;
          curl -s https://config.peerdas-devnet-1.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/metadata/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/metadata/genesis.ssz ];
          then
            wget -O /data/network-config/metadata/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/metadata/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/metadata/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/metadata/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/metadata/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/metadata/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/metadata/bootstrap_nodes2.txt;
          mv /data/network-config/metadata/bootstrap_nodes2.txt /data/network-config/metadata/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/metadata/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
